export const HTTP_STATUS_CODES  = {
  CONTINUE: { status: 100, phrase: "Continue" },
  SWITCHING_PROTOCOLS: { status: 101, phrase: "Switching Protocols" },
  PROCESSING: { status: 102, phrase: "Processing" },
  OK: { status: 200, phrase: "OK" },
  CREATED: { status: 201, phrase: "Created" },
  ACCEPTED: { status: 202, phrase: "Accepted" },
  NON_AUTHORITATIVE_INFORMATION: {
    status: 203,
    phrase: "Non Authoritative Information",
  },
  NO_CONTENT: { status: 204, phrase: "No Content" },
  RESET_CONTENT: { status: 205, phrase: "Reset Content" },
  PARTIAL_CONTENT: { status: 206, phrase: "Partial Content" },
  MULTI_STATUS: { status: 207, phrase: "Multi-Status" },
  MULTIPLE_CHOICES: { status: 300, phrase: "Multiple Choices" },
  MOVED_PERMANENTLY: { status: 301, phrase: "Moved Permanently" },
  MOVED_TEMPORARILY: { status: 302, phrase: "Moved Temporarily" },
  SEE_OTHER: { status: 303, phrase: "See Other" },
  NOT_MODIFIED: { status: 304, phrase: "Not Modified" },
  USE_PROXY: { status: 305, phrase: "Use Proxy" },
  TEMPORARY_REDIRECT: { status: 307, phrase: "Temporary Redirect" },
  PERMANENT_REDIRECT: { status: 308, phrase: "Permanent Redirect" },
  BAD_REQUEST: { status: 400, phrase: "Bad Request" },
  UNAUTHORIZED: { status: 401, phrase: "Unauthorized" },
  PAYMENT_REQUIRED: { status: 402, phrase: "Payment Required" },
  FORBIDDEN: { status: 403, phrase: "Forbidden" },
  NOT_FOUND: { status: 404, phrase: "Not Found" },
  METHOD_NOT_ALLOWED: { status: 405, phrase: "Method Not Allowed" },
  NOT_ACCEPTABLE: { status: 406, phrase: "Not Acceptable" },
  PROXY_AUTHENTICATION_REQUIRED: {
    status: 407,
    phrase: "Proxy Authentication Required",
  },
  REQUEST_TIMEOUT: { status: 408, phrase: "Request Timeout" },
  CONFLICT: { status: 409, phrase: "Conflict" },
  GONE: { status: 410, phrase: "Gone" },
  LENGTH_REQUIRED: { status: 411, phrase: "Length Required" },
  PRECONDITION_FAILED: { status: 412, phrase: "Precondition Failed" },
  REQUEST_TOO_LONG: { status: 413, phrase: "Request Entity Too Large" },
  REQUEST_URI_TOO_LONG: { status: 414, phrase: "Request-URI Too Long" },
  UNSUPPORTED_MEDIA_TYPE: { status: 415, phrase: "Unsupported Media Type" },
  REQUESTED_RANGE_NOT_SATISFIABLE: {
    status: 416,
    phrase: "Requested Range Not Satisfiable",
  },
  EXPECTATION_FAILED: { status: 417, phrase: "Expectation Failed" },
  IM_A_TEAPOT: { status: 418, phrase: "I'm a teapot" },
  INSUFFICIENT_SPACE_ON_RESOURCE: {
    status: 419,
    phrase: "Insufficient Space on Resource",
  },
  METHOD_FAILURE: { status: 420, phrase: "Method Failure" },
  UNPROCESSABLE_ENTITY: { status: 422, phrase: "Unprocessable Entity" },
  LOCKED: { status: 423, phrase: "Locked" },
  FAILED_DEPENDENCY: { status: 424, phrase: "Failed Dependency" },
  PRECONDITION_REQUIRED: { status: 428, phrase: "Precondition Required" },
  TOO_MANY_REQUESTS: { status: 429, phrase: "Too Many Requests" },
  REQUEST_HEADER_FIELDS_TOO_LARGE: {
    status: 431,
    phrase: "Request Header Fields Too Large",
  },
  UNAVAILABLE_FOR_LEGAL_REASONS: {
    status: 451,
    phrase: "Unavailable For Legal Reasons",
  },
  INTERNAL_SERVER_ERROR: { status: 500, phrase: "Internal Server Error" },
  NOT_IMPLEMENTED: { status: 501, phrase: "Not Implemented" },
  BAD_GATEWAY: { status: 502, phrase: "Bad Gateway" },
  SERVICE_UNAVAILABLE: { status: 503, phrase: "Service Unavailable" },
  GATEWAY_TIMEOUT: { status: 504, phrase: "Gateway Timeout" },
  HTTP_VERSION_NOT_SUPPORTED: {
    status: 505,
    phrase: "HTTP Version Not Supported",
  },
  INSUFFICIENT_STORAGE: { status: 507, phrase: "Insufficient Storage" },
  NETWORK_AUTHENTICATION_REQUIRED: {
    status: 511,
    phrase: "Network Authentication Required",
  },
};
